"""rev1 autogen Initial wheel_specs table

Revision ID: 5d3f4f93b087
Revises: 
Create Date: 2025-07-13 19:52:34.869963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3f4f93b087'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_number', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=False),
    sa.Column('submitted_date', sa.String(), nullable=False),
    sa.Column('axle_box_housing_bore_dia', sa.String(), nullable=True),
    sa.Column('bearing_seat_diameter', sa.String(), nullable=True),
    sa.Column('condemning_dia', sa.String(), nullable=True),
    sa.Column('intermediate_wwp', sa.String(), nullable=True),
    sa.Column('last_shop_issue_size', sa.String(), nullable=True),
    sa.Column('roller_bearing_bore_dia', sa.String(), nullable=True),
    sa.Column('roller_bearing_outer_dia', sa.String(), nullable=True),
    sa.Column('roller_bearing_width', sa.String(), nullable=True),
    sa.Column('tread_diameter_new', sa.String(), nullable=True),
    sa.Column('variation_same_axle', sa.String(), nullable=True),
    sa.Column('variation_same_bogie', sa.String(), nullable=True),
    sa.Column('variation_same_coach', sa.String(), nullable=True),
    sa.Column('wheel_disc_width', sa.String(), nullable=True),
    sa.Column('wheel_gauge', sa.String(), nullable=True),
    sa.Column('wheel_profile', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_number')
    )
    op.create_index(op.f('ix_wheel_specs_id'), 'wheel_specs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wheel_specs_id'), table_name='wheel_specs')
    op.drop_table('wheel_specs')
    # ### end Alembic commands ###
